version: '3.9'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: doggydb
      MYSQL_ROOT_PASSWORD: geheim
    ports:
      - "3306:3306"
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /docker/minio:/data
    restart: unless-stopped